version: "3"

networks:
  winx-network:

volumes:
  mongo-volume:
    driver: local

services:
  winx_db:
    image: mongo:latest
    container_name: "winx_db"
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./mongo-init.js:/docker-entrypoint.initdb.d/mongo-init.js:ro
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
    networks:
      - winx-network
  
  stella:
    build: ./stella
    container_name: stella
    restart: unless-stopped
    command: uvicorn stella.api.main:api --host 0.0.0.0 --port 8000
    environment:
      - VIRTUAL_HOST=localhost
    ports:
      - 8000:8000
    expose:
      - "8000"
    depends_on:
      - winx_db
    networks:
      - winx-network
    env_file:
      - stella/.env
